name: fstore
publish_to: "none"
description: Mobile commerce app by Flutter

# Release version: v4.1.0 (Do not change this line)
# A version number is three numbers separated by dots, like 1.2.43 - followed by an optional build number separated by a +.
# In Android, build-name is used as versionName while build-number used as versionCode.Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion. Read more about iOS versioning at https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3000

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  inspireui: 2.1.0

  flutterflow:
    path: packages/flutterflow/
  flux_firebase:
    path: packages/flux_firebase/

  # Base
  flutter_localization: ^0.2.0
  intl: any
  crypto: 3.0.3
  path_provider: ^2.1.3
  url_launcher: 6.2.6
  flutter_secure_storage: ^9.2.2
  hive: 2.2.3
  hive_flutter: 1.1.0
  http: ^1.1.0
  dio: ^5.2.1
  http_auth: 1.0.4
  share: 2.0.4
  tuple: 2.0.2
  collection: any
  quiver: 3.2.1
  async: 2.11.0
  html: 0.15.4
  vector_math: 2.1.4
  path: 1.9.0
  flutter_svg: 2.0.10+1
  notification_permissions: 0.6.1
  flutter_local_notifications: 14.1.5
  onesignal_flutter: ^5.2.0
  new_version_plus: 0.0.11

  # STATE MANAGEMENT
  provider: 6.1.2
  get_it: ^7.7.0

  # SPLASH SCREEN, ONBOARD
  lottie: ^3.1.2
  rive: ^0.13.4

  # WEB TOOLS
  html_unescape: 2.0.0
  webview_flutter: 4.7.0
  webview_flutter_web: 0.2.2+4
  responsive_builder: 0.7.0
  flutter_inappwebview: 6.0.0
  # Fix issue with flutter_inappwebview (Blank screen on Android)
  webview_flutter_android: 3.16.1

  # HTML render
  flutter_widget_from_html_core: ^0.14.12
  fwfh_svg: 0.8.1
  fwfh_cached_network_image: 0.14.2
  fwfh_url_launcher: 0.9.0+4
  #  fwfh_chewie: 0.7.1+2 # accentColor issue
  fwfh_webview: ^0.15.0

  # VIDEO
  video_player: ^2.8.6
  youtube_player_iframe: 5.1.2

  # MAP
  google_maps_flutter: 2.6.1
  # constraints for google_maps_flutter
  google_maps_flutter_android: ^2.8.0
  google_maps_flutter_ios: 2.6.0
  location: ^6.0.2
  geocoding: ^3.0.0

  # AUTHENTICATION
  local_auth: 2.2.0
  the_apple_sign_in: 1.1.1
  flutter_facebook_auth: ^7.0.0
  google_sign_in: 6.2.1
  sms_autofill: 2.3.1
  permission_handler: ^11.3.1

  # FILES, IMAGES
  file_picker: ^8.0.3
  cached_network_image: 3.3.1
  image: ^4.2.0
  transparent_image: 2.0.1
  image_picker: ^1.1.1
  flutter_native_image: 0.0.6+1
  flutter_cache_manager: ^3.3.2
  wechat_assets_picker: ^9.0.3
  photo_manager: ^3.1.1

  # TOOLS
  google_fonts: ^6.2.1
  random_string: 2.3.1
  json_annotation: ^4.9.0
  freezed_annotation: 2.4.1
  timeago: 3.6.1
  universal_platform: ^1.1.0
  uuid: ^4.4.0
  easy_debounce: 2.0.3
  devicelocale: ^0.7.1
  visibility_detector: 0.4.0+2
  rate_my_app: ^2.1.0
  flutter_linkify: 6.0.0
  gms_check: 1.0.2
  google_mobile_ads: ^5.1.0
  speech_to_text: 6.6.0 # block by qr_code_scanner
  flutter_keyboard_visibility: 6.0.0
  app_tracking_transparency: ^2.0.5
  facebook_app_events: 0.19.2

  # UI
  flutter_spinkit: ^5.2.1
  smooth_page_indicator: 1.1.0
  animated_text_kit: 4.2.2
  flash: 3.1.0
  flutter_staggered_grid_view: 0.7.0
  pin_code_fields: 8.0.1
  country_pickers: 3.0.1
  dropdown_search: 5.0.6
  intro_slider: 4.2.1
  extended_image: 8.2.0
  dotted_decoration: 2.0.0
  awesome_card: 1.1.7
  qr_code_scanner: 1.0.1
  sticky_headers: 0.3.0+2
  jumping_dot: 0.0.6
  fl_chart: ^0.68.0
  tiktoklikescroller: 0.2.6
  readmore: ^3.0.0
  flutter_animate: 4.5.0
  # Customize to adapt with the project
  flutter_async_autocomplete:
    git:
      url: https://github.com/inspireui/flutter_async_autocomplete.git
      ref: e4099b4ae69b9a02f174ca0e4db6b1d2c356a924
  scrollable_positioned_list: 0.3.8
  country_code_picker: 3.0.0
  carousel_slider: 4.2.1
  rect_getter: 1.1.0
  scroll_to_index: 3.0.1
  flutter_zoom_drawer: 3.2.0
  infinite_carousel: 1.1.1
  timezone: ^0.9.3
  sliver_tools: ^0.2.12
  flutter_staggered_animations: 1.1.1
  flutter_lazy_indexed_stack: 0.0.6
  flutter_calendar_carousel:
    git:
      url: https://github.com/dooboolab-community/flutter_calendar_carousel.git
      ref: 3ad0085c36c4c974ea0262e769e3eed2eb6cc479
  bot_toast: ^4.1.3

  ### Native Payment
  razorpay_flutter: 1.3.6
  paytm_allinonesdk: # Fix conflict return callback url with stripe
    git:
      url: https://github.com/inspireui/paytm_allinonesdk.git
      ref: c885ad07605d7ba012c8daec443bb7ed9873e798
  # Outdated dependency webview_flutter: 4.7.0
  pay_with_paystack:
    git:
      url: https://github.com/inspireui/pay_with_paystack
      ref: 34163d42305f92e4071ab2fcf6fc8c16429397f5
  # This package is discontinued
  flutter_paystack:
    git:
      url: https://github.com/inspireui/flutter_paystack.git
      ref: d5355aa84e0884730e259d6c46f5e5dcf46e658a
  # This package is discontinued
  flutterwave_standard:
    git:
      url: https://github.com/inspireui/Flutterwave-v3.git
      ref: upgrade/deps

  #### For Shopify GraphQL
  graphql: 5.2.0-beta.7

  ### Flutter 3 fix warning
  intl_phone_number_input: # custom feature for phone number
    git:
      url: https://github.com/inspireui/intl_phone_number_input
      ref: 7408d78d555b0516feb051f58d7053caff082cd0
  # This package is discontinued
  flutter_swiper_null_safety:
    git:
      url: https://github.com/inspireui/flutter_swiper_null_safety
      ref: 18e8d2d642ff9e0013fc4477c6d64c52732b463a
  # This package is discontinued
  flare_flutter:
    git:
      url: https://github.com/inspireui/Flare-Flutter.git
      ref: fd4bcba22aae4c028286e453deeb78f3311e689a
      path: flare_flutter
  # This package is discontinued
  pull_to_refresh:
    git:
      url: https://github.com/inspireui/flutter_pull_to_refresh
      ref: 24df296e282cd8b4ea8d3a5e171f4156a0295d1b
  multiple_localization: 0.5.0

  ###---- Some extra feature is disable by default -----###
  ### ðŸ’³ Facebook Ads
  ### Search "Enable Facebook Ads" & uncomment to use  - https://tppr.me/9Pkf9
  # facebook_audience_network: 1.0.1

  ### â¬‡ï¸ Enable In App Update on Android feature
  ### Uncomment file lib/common/tools/in_app_update_for_android.dart
  in_app_update: 4.2.2
  meta_seo: 3.0.9

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

### Enable to use Flutter Test Driver
#  flutter_driver:
#    sdk: flutter
#  test: 1.16.5
#  dependency_validator: 3.2.2  # pub run dependency_validator

### Enable Generate Icon library
  flutter_launcher_icons: 0.13.1

#  Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/states/
    - lib/config/stories/
    - lib/config/us_store/
    - lib/config/vi_store/
    - assets/icons/brands/
    - assets/icons/credit_cards/
    - assets/icons/tabs/
    - assets/icons/payment/
    - assets/icons/logins/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/map_styles/
    - assets/html/
    - google_fonts/

### Uncomment to use custom font
#  fonts:
#    - family: Your Custom Font
#      fonts:
#      - asset: google_fonts/GE-Hili-Book.ttf

flutter_intl:
  enabled: true
  use_deferred_loading: true
